config/routes.rb
Rails.application.routes.draw do
  get :login, to: 'sessions#new'
  get :logout, to: 'sessions#destroy'
  
  resources :sessions
  resources :users
  resources :entries
  resources :activations, only: [:edit]
  root 'entries#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ActiveRecord
  include AASM
  has_secure_password
  before_action :create_activation_code
  
  aasm do
    state :pending_activation, initial: true
    state :active
    state :removed
    
    
    event :activate do
      transitions from: :pending_activation, to: :active
    end
    
    event :remove do
      transitions from: [:pending_activation, :active], to: :removed
    end
  end
  
  private
  
  def create_activation_code
    self.activation_code = SecureRandom.urlsafe_base64(32)
  end
end

app/models/user_session.rb
class UserSession < Authlogic::Session::Base
  
end

app/controllers/activations_controller.rb
class ActivationsController < ApplicationController
  def edit
    user = User.find_by activation_code: params[:id]
    
    if user
      user.update_attributes activation_code: nil, activated_at: Time.zone.now
      user.activate!
      redirect_to login_path, notice: 'Account activated! Please sign in.'
    else
      redirect_to root_path, error: 'Invalid activation link.'
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user
  
  private
  
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    user = User.find_by email: params[:login][:email]
    
    if user && user.active?
      if user.authenticate(params[:login][:password])
        sessions[:user_id] = user.id
        redirect_to root_path, notice: 'Successfully logged in'
      else
        flash.now.alert = 'Invalid email or password'
      end
    else
      redirect_to root_path, alert: 'Account not activated.'
    end
  end
  
end

app/controllers/user.rb
class User < ActiveRecord
  include AASM
  has_secure_password
  
  aasm do 
    state :pending_activation, initial: true
    state :active
    state :removed
    
    event :activate do
      transitions from: :pending_activation, to: :active
    end
    
    event :remove do
      transitions from: [:pending_activation, :active], to: :removed
    end
  end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  # GET /user_sessions/new
  def new
    @user_session = UserSession.new
  end

  # POST /user_sessions
  # POST /user_sessions.json
  def create
    @user_session = UserSession.new(user_session_params)

    respond_to do |format|
      if @user_session.save
        format.html { redirect_to root_path, notice: 'What up dawg?' }
        format.json { render :show, status: :created, location: @user_session }
      else
        format.html { render :new }
        format.json { render json: @user_session.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_sessions/1
  # DELETE /user_sessions/1.json
  def destroy
    @user_session.find
    @user_session.destroy
    respond_to do |format|
      format.html { redirect_to root_path, notice: 'Peace out, yo!' }
      format.json { head :no_content }
    end
  end

  private
    # Never trust parameters from the scary internet, only allow the white list through.
    def user_session_params
      params.require(:user_session).permit(:email, :password)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new params[:user]
  end
  
  def create
    @user = User.new user_params
    if @user.save
      redirect_to root_path, notice: 'Successfully created user.'
    else
      render :new
    end
  end
  
  private
  
  def user_params
    params.require(:user).permit :email, :password, :password_confirmation
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user
    return @current_user if defined? @current_user
    @current_user = current_user_session && current_user_session.record
  end
  
  def current_user_session
    return @current_user_session if defined? @current_user_session
    @current_user_session = UserSession.find
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_navigation_links.html.erb
<li>
  <%= link_to 'Entries', entries_path %>
</li>
<li>
  <% if current_user %>
    <%= link_to 'Logout', logout_path %>
  <% else %>
    <%= link_to 'Login', login_path %>
  <% end %>
</li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsAuth</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/user_sessions/_form.html.erb
<%= form_with(model: user_session, local: true) do |form| %>
  <% if user_session.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user_session.errors.count, "error") %> prohibited this user_session from being saved:</h2>

      <ul>
      <% user_session.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :username %>
    <%= form.text_field :username %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.text_field :password %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/user_sessions/edit.html.erb
<h1>Editing User Session</h1>

<%= render 'form', user_session: @user_session %>

<%= link_to 'Show', @user_session %> |
<%= link_to 'Back', user_sessions_path %>

app/views/user_sessions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>User Sessions</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Password</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @user_sessions.each do |user_session| %>
      <tr>
        <td><%= user_session.username %></td>
        <td><%= user_session.password %></td>
        <td><%= link_to 'Show', user_session %></td>
        <td><%= link_to 'Edit', edit_user_session_path(user_session) %></td>
        <td><%= link_to 'Destroy', user_session, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User Session', new_user_session_path %>

app/views/user_sessions/new.html.erb
<h1>New User Session</h1>

<%= render 'form', user_session: @user_session %>

<%= link_to 'Back', user_sessions_path %>

app/views/user_sessions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @user_session.username %>
</p>

<p>
  <strong>Password:</strong>
  <%= @user_session.password %>
</p>

<%= link_to 'Edit', edit_user_session_path(@user_session) %> |
<%= link_to 'Back', user_sessions_path %>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :username %>
    <%= form.text_field :username %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :crypted_password %>
    <%= form.text_field :crypted_password %>
  </div>

  <div class="field">
    <%= form.label :password_salt %>
    <%= form.text_field :password_salt %>
  </div>

  <div class="field">
    <%= form.label :persistence_token %>
    <%= form.text_field :persistence_token %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Email</th>
      <th>Crypted password</th>
      <th>Password salt</th>
      <th>Persistence token</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= user.email %></td>
        <td><%= user.crypted_password %></td>
        <td><%= user.password_salt %></td>
        <td><%= user.persistence_token %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>Users#new</h1>
<%= simple_form_for @user do |f| %>
  <%= f.input :email %>
  <%= f.input :password %>
  <%= f.input :password_confirmation %>
  <%= f.button :submit %>
<% end %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @user.username %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Crypted password:</strong>
  <%= @user.crypted_password %>
</p>

<p>
  <strong>Password salt:</strong>
  <%= @user.password_salt %>
</p>

<p>
  <strong>Persistence token:</strong>
  <%= @user.persistence_token %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>